### ISSUE TITLE
Why do we return all apps even though method suppose to select an app and return pagearray for that app? 

### ISSUE THREAD

**Issue by yaphatak** [appium/appium-remote-debugger#37]
https://github.com/appium/appium-remote-debugger/blob/master/lib/remote-debugger.js#L273-L282. 
Since we are returning all apps it doesn't even matter logic that we have for selecting app.

**Comment by imurchie** [comment]
This was added in order to handle WKWebviews.

**Comment by yaphatak** [comment]
Is it fine if I submit PR with selectApp taking argument like `WKWebviews=true` and for `false` only return selected page

**Comment by imurchie** [comment]
There is no way for the calling code to know what kind of webview it is.

What is the problem that is happening from having this?

**Comment by yaphatak** [comment]
Well whole idea of selecting app is lost here. And I still get webviews with `empty` and `about:blank` urls. 
I was thinking I can send via capabilities and pass it on in xcuitest/ios driver.

**Comment by imurchie** [comment]
Sending as a capability would work. Unless there are a mixture of types in an application.

Can we not filter any empty urls? `about:blank` ones are valid, though.

**Comment by yaphatak** [comment]
Yes it would not work with mixture webvierws and thats why default behavior should be as it is now.
Filtering empty url is possible but will that break WKWebView scenario?

**Comment by imurchie** [comment]
Filtering empty urls should not break the WKWebview support.

**Comment by yaphatak** [comment]
Ok, I will make that change then. I am not sure what this do though https://github.com/appium/appium-remote-debugger/blob/master/lib/remote-debugger.js#L261-L267

**Comment by yaphatak** [comment]
[This](https://github.com/appium/appium-remote-debugger/pull/38/files) is not final version but does this make sense ? also I still dont know what does [this](https://github.com/appium/appium-remote-debugger/blob/master/lib/remote-debugger.js#L261-L267) do

**Comment by imurchie** [comment]
That bit (lines 261-267) waits for all the apps that we have been told about to have a page associated with them. The remote debugger notifies us that there is an app, but only later does it say what page (or pages) are in the app. So we store a promise for each app when it is sent to us, and then, before returning, wait for them to be fulfilled.

**Comment by rkavalap** [comment]
@yaphatak closing this issue. I see you already have a PR for this one. If you need a tracking bug for this, we can create one in the main appium repo.
