### ISSUE TITLE
Appium hangs on unresponsive webview

### ISSUE THREAD

**Issue by ssynix** [appium/appium-remote-debugger#42]
Our app uses WKWebviews and has built a number of custom functionality surrounding URL navigation. For example, if the app has no internet access, the webview navigates to a native page which displays the proper error message. Navigating to certain URLs within the webview also triggers the creation of a new webview and disabling the original webview.

Appium naturally does not expect this behavior, so I've resorted to handling URL navigation by executing javascript, as I don't believe it is logical for Appium to handle our convoluted webview navigation logic. The issue that I've run into is that if the app ends up in one of these unresponsive webviews, or if the URL navigation is interrupted by a native page, Appium hangs since IWDP never returns a response.

The simplest solution from my end is to [add a timeout](https://github.com/appium/appium-remote-debugger/blob/master/lib/webkit-rpc-client.js#L102) to the promise that's expecting a response from the webview, which results in an exception that I can catch and handle appropriately from my end.

Let me know if this is the right solution, and whether it has any potential side effects on the rest of the remote-debugger that I should be aware of. I'm definitely open to submitting the PR.

**Comment by imurchie** [comment]
I think that sounds like a good idea, in general. If the promise is correctly, and the data handlers are handled correctly (probably best to move the `then` handler into a `finally` [here](https://github.com/appium/appium-remote-debugger/blob/master/lib/webkit-rpc-client.js#L94)), it should not have side effects.

**Comment by rkavalap** [comment]
@ssynix  Closing this issue, since your PR for this is merged. If you believe something needs to be enhanced, can you open a new issue in main appium repo.
